
# local {
# 	max_clients	999;
# }

# global {
# 	server_listen			9999;
# 	server_name				255.255.255.255;
# 	server_upload			on;
# 	server_clientbodymax	9999;
# 	server_error			file_path.html;

# 	location_method			on;
# 	location_root			file_path.html;
# 	location_index			file_path.html;
# 	location_cookie			on;
# 	location_autoindex		on;

# 	redir_valid				on;
# 	redir_errorcode			9999;
# 	redir_path				file_path.html;
# }

# server {

# 	listen		9999;
# 	name 		255.255.255.255;

# 	client_body_max	9999;
	
# 	error_page		file_path.html;

# 	location {
# 		methods		METHOD METHOD on METHOD off;
# 		cgi			.extension .extension;
# 		error;
# 		error		9999 file_path.html;
#		root		directory_path/;
#		index		file_path.html;
#		cookie		on;
#		autoindex	on;
#		upload	directory_path/;
#		return;
#		return		9999 file_path.html;
# 	}
# }


local {
    max_clients 1024; server
}

global {
	location_cookie			off;
	location_method			on;
	location_root			html;
	location_index			index.html;
	location_autoindex		off;

	redir_valid				off;
	redir_errorcode			301;
	redir_path				html/errors/error2.html;
}

server {

	listen		8080;
	name 		127.0.0.1;

	client_body_max	500000;
	
	error_page		html/errors/error.html;
	error_page 404 html/errors/404_error.html;

	location /
	{
		methods	DELETE off;
		root html;
		index index.html;
		cgi .sh .py .out;
		upload upload/pictures/;
		return 302 index.html;
	}

	location /cgi
	{
		
	}

	location /todelete
	{
		root html;
		return 302 index.html;
		# autoindex on;
	}

	location /css/style/theme
	{
		cookie	on;
		methods DELETE off;
		root html;
		index theme.css;
	}

	location /css/style/font
	{
		cookie	on;
		methods DELETE off;
		root html;
		index font.css;
	}
}
