local {
    max_clients 256;
}

global {
    location_cookie      off;
    location_method      on;
    location_root        html;
    location_index       index.html;
    location_autoindex   off;

    redir_valid          off;
    redir_errorcode      302;
    redir_path           /index.html;
}

server {
	listen 8080;
	name 127.0.0.1;

	client_body_max 500000;
	error_page html/errors/error.html;
	error_page 404 html/errors/404_error.html;

	# Route racine
	location / 
	{
		root html;
		return 302 /get.html;
		index index.html;
		upload upload/pictures/;
		cgi .py .sh .cgi .out;
		methods DELETE off;
	}

	# Redirection simple
	location /old 
	{
		return 302 /methods.html;
		index index.html;
	}

	# Autoindex sur un dossier de test
	location /todelete 
	{
		root html;
		autoindex on;
		methods DELETE on;
	}

	# CGI
	location /cgi 
	{
		root cgi;
		index my_cgi.py;
		cgi .py .sh .cgi .out;
		methods GET POST on DELETE off;
	}

	# Exemple cookie-based css
	location /style 
	{
		root html/css/style/;
		index style.css;
		cookie on;
		methods DELETE off;
	}

	location /theme
	{
		root html/css/style/theme/;
		index theme.css;
		cookie on;
		methods DELETE off;
	}

	location /font 
	{
		root html/css/style/font/;
		index font.css;
		cookie on;
		methods DELETE off;
	}
}
