local {
    max_clients 1024; server
}

global {


}

global {

	server_listen			8282;
	server_clientbodymax	500000;
	server_error			html/errors/error.html; dedede
	# server_error			404 page; //TODO

	location_cookie			off;
	location_method			on;
	# location_method			DELETE	off; //TODO
	location_root			html;
	location_index			index.html;
	location_autoindex		on;

	redir_valid				off;
	redir_errorcode			301;
	redir_path				html/errors/error2.html;
}


server {
	listen 8080;
	name localhost;

	location /directory 
	{
		error 404 html/errors/404_error.html;
		root /cgi;
		# index index.html;
		index my_cgi.py;
		cgi .sh .py;
		upload upload/login/;
	}

	location /css/style
	{
		cookie	off;
		root	html;
		index	style.css;
		cgi		.sh .c;
	}

	location /css/style/theme
	{
		cookie	on;
		root html;
		index theme.css;
	}

	location /css/style/font
	{
		cookie	on;
		root html;
		index font.css;
	}
}


server {
	listen	8081;
	name 	127.0.0.2;
}

# server {
# 	listen	8181;
# 	name 	127.0.0.3;
# }

# server {
# 	server
# }
